### ISSUE TITLE
The extension doesn't work

### ISSUE THREAD

**Issue by jievince** [lighttiger2505/vscode-sqls#7]
![image](https://user-images.githubusercontent.com/38901892/185785576-b407cccf-ec1e-46eb-88ad-1641deb5bcb1.png)
![image](https://user-images.githubusercontent.com/38901892/185785591-a85fd4c2-1fb1-4007-99b9-2aaef217e5ae.png)

![image](https://user-images.githubusercontent.com/38901892/185785628-e9d81a1a-a340-413f-a3b6-4fd0958bed24.png)

**Comment by senkenn** [comment]
Hi, @jievince . This extension is not updating so I created new sqls extension and fixed this problem!
https://marketplace.visualstudio.com/items?itemName=senken.sqlsurge

Try to search with `SENKEN.sqlsurge` in extensions pane and install :smile:

**Comment by jievince** [comment]
> Hi, @jievince . This extension is not updating so I created new sqls extension and fixed this problem! https://marketplace.visualstudio.com/items?itemName=senken.sqlsurge
> 
> Try to search with `SENKEN.sqlsurge` in extensions pane and install 😄

Ok, I'll try it.
